### ISSUE TITLE
system-monitor container crashes 

### ISSUE THREAD

**Issue by bart-roos** [madhuakula/kubernetes-goat#137]
The system-monitor scenario container (Container escape to the host system) keeps crashing in my setup. I am running Kubernetes Goat from a Parallels CentOS VM on a Macbook Pro M2 (ARM platform). I did the usual setup:

```
git clone https://github.com/madhuakula/kubernetes-goat.git
cd kubernetes-goat
bash setup-kubernetes-goat.sh
```

After the setup, the system-monitor pod keeps crashing:

```
[bart@localhost kubernetes-goat]$ kubectl get pods
NAME                                              READY   STATUS             RESTARTS         AGE
batch-check-job-67stc                             0/1     Completed          0                58m
build-code-deployment-7b558b489f-zvkn9            1/1     Running            1 (34m ago)      58m
health-check-deployment-678cc744c8-7bwqt          1/1     Running            1 (34m ago)      58m
hello-k8s-77c964f6d9-kx4bk                        1/1     Running            1 (34m ago)      83m
hidden-in-layers-bkzkk                            0/1     Error              0                58m
hidden-in-layers-r294q                            1/1     Running            0                19m
internal-proxy-deployment-7955c45559-6bbt8        2/2     Running            3 (34m ago)      58m
kubernetes-goat-home-deployment-578759495-mrs75   1/1     Running            1 (34m ago)      58m
poor-registry-deployment-c96986875-jrqf9          1/1     Running            1 (34m ago)      58m
system-monitor-deployment-7d665b6fdf-92p5n        0/1     CrashLoopBackOff   15 (3m18s ago)   58m
```

This is the output of `kubectl describe pod`

```
[bart@localhost kubernetes-goat]$ kubectl describe pod system-monitor-deployment-7d665b6fdf-92p5n
Name:             system-monitor-deployment-7d665b6fdf-92p5n
Namespace:        default
Priority:         0
Service Account:  default
Node:             minikube/192.168.49.2
Start Time:       Fri, 08 Sep 2023 15:20:40 +0200
Labels:           app=system-monitor
                  pod-template-hash=7d665b6fdf
Annotations:      <none>
Status:           Running
IP:               10.244.0.21
IPs:
  IP:           10.244.0.21
Controlled By:  ReplicaSet/system-monitor-deployment-7d665b6fdf
Containers:
  system-monitor:
    Container ID:   docker://5ef985cda06081bd7ccbf0d3495496361cea08f387fab9f71159b32aaf4077ef
    Image:          madhuakula/k8s-goat-system-monitor
    Image ID:       docker-pullable://madhuakula/k8s-goat-system-monitor@sha256:06b58bd080201ea0d4048befdd2159f384b61ce457a5a96e3001db629b5caa40
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 08 Sep 2023 16:26:04 +0200
      Finished:     Fri, 08 Sep 2023 16:26:04 +0200
    Ready:          False
    Restart Count:  17
    Limits:
      cpu:     20m
      memory:  50Mi
    Requests:
      cpu:     20m
      memory:  50Mi
    Environment:
      K8S_GOAT_VAULT_KEY:  <set to the key 'k8sgoatvaultkey' in secret 'goatvault'>  Optional: false
    Mounts:
      /host-system from host-filesystem (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-qthvk (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  host-filesystem:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:
  kube-api-access-qthvk:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       67m                    default-scheduler  Successfully assigned default/system-monitor-deployment-7d665b6fdf-92p5n to minikube
  Normal   Pulled          66m                    kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 4.636044887s (57.85430525s including waiting)
  Normal   Pulled          66m                    kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 1.197244245s (6.398591877s including waiting)
  Normal   Pulled          65m                    kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 1.198137167s (1.198149793s including waiting)
  Normal   Created         65m (x4 over 66m)      kubelet            Created container system-monitor
  Normal   Pulled          65m                    kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 1.187372558s (1.187406391s including waiting)
  Normal   Started         65m (x4 over 66m)      kubelet            Started container system-monitor
  Normal   Pulling         64m (x5 over 67m)      kubelet            Pulling image "madhuakula/k8s-goat-system-monitor"
  Normal   Pulled          64m                    kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 1.204099164s (1.204142997s including waiting)
  Warning  BackOff         52m (x64 over 65m)     kubelet            Back-off restarting failed container system-monitor in pod system-monitor-deployment-7d665b6fdf-92p5n_default(2b5b82d0-131c-4d35-8b7c-45ca43f15ab1)
  Warning  Failed          47m                    kubelet            Failed to pull image "madhuakula/k8s-goat-system-monitor": rpc error: code = Unknown desc = Error response from daemon: Get "https://registry-1.docker.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Normal   SandboxChanged  28m                    kubelet            Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          28m                    kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 1.170037784s (6.733465063s including waiting)
  Normal   Pulled          28m                    kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 1.139940465s (1.139953464s including waiting)
  Normal   Pulled          27m                    kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 3.144573825s (3.144595783s including waiting)
  Normal   Pulling         26m (x4 over 28m)      kubelet            Pulling image "madhuakula/k8s-goat-system-monitor"
  Normal   Created         26m (x4 over 28m)      kubelet            Created container system-monitor
  Normal   Started         26m (x4 over 28m)      kubelet            Started container system-monitor
  Normal   Pulled          26m                    kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 1.158015604s (1.158047562s including waiting)
  Warning  BackOff         3m29s (x116 over 28m)  kubelet            Back-off restarting failed container system-monitor in pod system-monitor-deployment-7d665b6fdf-92p5n_default(2b5b82d0-131c-4d35-8b7c-45ca43f15ab1)
```

And `kubectl logs` is showing:

```
exec /usr/local/bin/gotty: exec format error
```

Any ideas how to fix this or further troubleshoot the issue?

**Comment by xvnpw** [comment]
Hi. I have very similar case. System monitor is crashing with error:

```bash
$ kubectl logs system-monitor-deployment-7d665b6fdf-898f8 
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x37b713, 0x9)
	/usr/local/go/src/runtime/panic.go:566 +0x78
runtime.newosproc(0x10824000, 0x10833fe0)
	/usr/local/go/src/runtime/os_linux.go:160 +0x1b0
runtime.newm(0x3b3394, 0x0)
	/usr/local/go/src/runtime/proc.go:1572 +0x12c
runtime.main.func1()
	/usr/local/go/src/runtime/proc.go:126 +0x24
runtime.systemstack(0x4e6f00)
	/usr/local/go/src/runtime/asm_arm.s:247 +0x80
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_arm.s:192 +0x4 fp=0x1081e7ac sp=0x1081e7a8
runtime.main()
	/usr/local/go/src/runtime/proc.go:127 +0x5c fp=0x1081e7d4 sp=0x1081e7ac
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:998 +0x4 fp=0x1081e7d4 sp=0x1081e7d4
```

my docker info:
```bash
 docker info
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.4
    Path:     /Users/x/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0-desktop.1
    Path:     /Users/x/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/x/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/x/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.7
    Path:     /Users/x/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/x/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/x/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.24.1
    Path:     /Users/x/.docker/cli-plugins/docker-scout

Server:
 Containers: 4
  Running: 2
  Paused: 0
  Stopped: 2
 Images: 105
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.3.13-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 15.61GiB
 Name: docker-desktop
 ID: 622db364-c7c9-4b85-9061-ecd2e794a6ea
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

**Comment by xvnpw** [comment]
Would be happy to get any ideas, how to fix it @madhuakula

**Comment by denizilhan** [comment]
Having the same issue here

**Comment by f0x1sland** [comment]
```bash 
root@153e5862180c:/tmp# file /usr/local/bin/gotty 
/usr/local/bin/gotty: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, with debug_info, not stripped
root@153e5862180c:/tmp# uname -m
aarch64
root@153e5862180c:/tmp# 
```
Hi there! That is happening because the binary gotty is 32 bit arm, but the system is 64 arm.

**Comment by madhuakula** [comment]
I pushed new images, now could you please check once?

**Comment by d3vilbug** [comment]
Hi @madhuakula 

Can you please share the updated image tag, I can't find it here. 

> https://hub.docker.com/r/madhuakula/k8s-goat-system-monitor/tags
